name: Build, Test & Publish
permissions:
  contents: read
  packages: write

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.x"
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Pack
        if: github.ref == 'refs/heads/main'
        run: dotnet pack -c release -o .
        env:
          GITHUB_BUILD_NUMBER: ${{github.run_number}}
      - name: Publish
        if: github.ref == 'refs/heads/main'
        run: dotnet nuget push OneOf.Monads.1.${{github.run_number}}.0.nupkg -k ${{secrets.NUGET_KEY}} -s https://api.nuget.org/v3/index.json
